#!/usr/bin/env python3
"""Install Bifrost's Codex launcher, or the legacy native footer preset.

Default: lay down a self-contained bin/share tree under --prefix so
`bifrost codex` can launch Codex inside a tmux session with the real
Bifrost gauges. --native-footer instead configures Codex's own built-in
status_line fields in config.toml (Python 3.11+ for tomllib either way).
"""

import argparse
import datetime
import json
import os
from pathlib import Path
import re
import tempfile
import tomllib


ITEMS = ["model-with-reasoning", "context-used", "five-hour-limit",
         "weekly-limit", "git-branch"]

PREFIX_MODULES = ("bifrost.py", "codex_status.py", "statusline.py")

LAUNCHER_SCRIPT = """#!/bin/sh
# Generated by bifrost-statusline's install-codex.py; do not edit by hand.
here="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
exec python3 "$here/../share/bifrost/bifrost.py" "$@"
"""


def configure(raw):
    """Preserve unrelated config and comments; fail closed for unusual TOML."""
    before = tomllib.loads(raw)
    expected = tomllib.loads(raw)
    expected.setdefault("tui", {})["status_line"] = ITEMS
    assignment = "status_line = " + json.dumps(ITEMS) + "\n"
    header = re.search(r"(?m)^\[tui\][ \t]*(?:#.*)?$", raw)
    if header:
        start = raw.find("\n", header.end())
        if start == -1:
            raw += "\n"
            start = len(raw) - 1
        start += 1
        next_header = re.search(r"(?m)^\s*\[", raw[start:])
        end = start + next_header.start() if next_header else len(raw)
        section = raw[start:end]
        setting = re.search(r"(?m)^status_line\s*=", section)
        if setting:
            # Replace the value through its last line, including multiline arrays.
            value_start = setting.start()
            value_end = section.find("\n", setting.end())
            value_end = len(section) if value_end == -1 else value_end + 1
            while True:
                try:
                    tomllib.loads(section[value_start:value_end])
                    break
                except tomllib.TOMLDecodeError as exc:
                    if value_end == len(section):
                        raise ValueError("Cannot safely replace status_line") from exc
                    newline = section.find("\n", value_end)
                    value_end = len(section) if newline == -1 else newline + 1
            section = section[:value_start] + assignment + section[value_end:]
        else:
            section = assignment + section
        result = raw[:start] + section + raw[end:]
    else:
        if "status_line" in before.get("tui", {}):
            raise ValueError("Move tui.status_line into a [tui] table before installing")
        result = raw.rstrip() + "\n\n[tui]\n" + assignment
    if tomllib.loads(result) != expected:
        raise ValueError("Refusing to change unrelated configuration")
    return result


def _install_native_footer(path):
    # Legacy preset: rewrite Codex's own config.toml status_line fields.
    raw = path.read_text() if path.exists() else ""
    result = configure(raw)
    if result == raw:
        print("Codex footer already configured.")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        backup = path.with_name(path.name + ".bak-" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S-%f"))
        fd = os.open(backup, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        with os.fdopen(fd, "w") as stream:
            stream.write(raw)
        print("Backup:", backup)
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as stream:
        stream.write(result)
    print("Configured native Codex footer. Restart Codex to load it.")
    print("Codex displays native fields; Bifrost's ANSI gauges require a command renderer.")


def _write_atomic(path, data, mode):
    # Same-directory temp file plus os.replace: a failure mid-write only
    # ever leaves behind (and cleans up) the temp file, never a partial
    # write at `path` itself.
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(dir=str(path.parent), prefix="." + path.name + "-")
    try:
        os.fchmod(fd, mode)
        with os.fdopen(fd, "wb") as stream:
            stream.write(data)
        os.replace(tmp_name, path)
    except BaseException:
        try:
            os.unlink(tmp_name)
        except OSError:
            pass
        raise


def _backup_if_changed(path, new_data):
    if path.exists() and path.read_bytes() != new_data:
        stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S-%f")
        backup = path.with_name(path.name + ".bak-" + stamp)
        backup.write_bytes(path.read_bytes())


def install_prefix(prefix):
    """Lay down a self-contained bin/share tree; never touch Codex config.

    Repeat installs overwrite only Bifrost's own files, byte-for-byte, and
    back up a changed file first. Everything else already under `prefix`
    is left exactly as it was.
    """
    root = Path(__file__).resolve().parent
    share = prefix / "share" / "bifrost"
    for name in PREFIX_MODULES:
        data = (root / name).read_bytes()
        target = share / name
        _backup_if_changed(target, data)
        _write_atomic(target, data, 0o644)

    launcher = prefix / "bin" / "bifrost"
    launcher_data = LAUNCHER_SCRIPT.encode()
    _backup_if_changed(launcher, launcher_data)
    _write_atomic(launcher, launcher_data, 0o755)


def main():
    """Install the prefix launcher by default, or the --native-footer preset."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--prefix", type=Path, default=Path.home() / ".local",
                        help="Install prefix for the bin/share launcher tree (default: ~/.local).")
    parser.add_argument("--native-footer", action="store_true",
                        help="Install the legacy Codex config.toml status_line preset instead.")
    parser.add_argument("--config", type=Path,
                        default=Path(os.environ.get("CODEX_HOME", Path.home() / ".codex")) / "config.toml",
                        help="config.toml path, only used with --native-footer.")
    args = parser.parse_args()

    if args.native_footer:
        _install_native_footer(args.config.expanduser())
        return

    prefix = args.prefix.expanduser()
    install_prefix(prefix)
    launcher = prefix / "bin" / "bifrost"
    print(f"Installed Bifrost launcher at {launcher}.")
    print("Codex's config.toml was not modified. Launch with:")
    print(f"  {launcher} codex")


if __name__ == "__main__":
    main()
